### PR TITLE
Cross references of limited depth

### PR DESCRIPTION
**Pull request by slavaschmidt**
Added support for recursive cross references with limited depth of nesting.

### CODE REVIEW

**Comment by adjohnson916** [comment]
@slavaschmidt Thanks. Can you explain the changes further? How does it differ from the maxDepth option?

**Comment by slavaschmidt** [comment]
@adjohnson916 sure, sorry, for lack of information.

This is indeed something with is supposed to get ```maxDepth``` working. Please take a look at new test cases. If two parts cross-reference each other and ```stopOnCircular ``` is ```false```, the tests would fail with ```StackOverflowException``` with old logic. Now each time the Processor goes one level deep in the reference chain, it checks if it's not running over allowed ```maxDepth```.

**Comment by adjohnson916** [comment]
@slavaschmidt Let me know if this is still relevant.

**Comment by slavaschmidt** [comment]
I'm not sure anymore, therefore it's probably better to close it and reopen in the case we will have issues related to that.

**Pull request closed without merging**
